version: "3.8"

services:
  db:
    image: postgres:14-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 54321:5432

  redis:
    image: redis:6.2.6

  web:
    build:
      context: .
    command: bash -c "
      chmod +x ./entrypoint.sh &&
      ./entrypoint.sh &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/Intership_project
    depends_on:
      - db
      - redis

  celery:
    build: .
    command: bash -c "celery -A Intership_project worker --loglevel=info --logfile=celery.log"
    env_file:
      - .env
    volumes:
      - .:/Intership_project
    depends_on:
      - web
      - redis

  celery_beat:
    build: .
    command: bash -c "celery -A Intership_project beat -l info"
    env_file:
      - .env
    volumes:
      - .:/Intership_project
    depends_on:
      - web
      - redis

  dashboard:
    build: .
    command: bash -c "celery -A Intership_project flower --port=5555"
    ports:
      - 5555:5555
    env_file:
      - .env
    volumes:
      - .:/Intership_project
    depends_on:
      - web
      - redis
      - celery