version: "3.8"

services:
  db:
    image: postgres:14-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 54321:5432

  web:
    build:
      context: .
    command: bash -c "
      chmod +x ./entrypoint.sh &&
      ./entrypoint.sh &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/Intership_project
    depends_on:
      - db
