version: "3.8"

services:
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod

  redis:
    image: redis:6.2.6

  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: bash -c "gunicorn Intership_project.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/Intership_project/static/
    expose:
      - 8000
    env_file:
      - .env.prod
    depends_on:
      - db
      - redis

  celery:
    build: .
    command: bash -c "celery -A Intership_project worker --loglevel=info --logfile=celery.log"
    env_file:
      - .env.prod
    volumes:
      - .:/Intership_project
    depends_on:
      - web
      - redis

  celery_beat:
    build: .
    command: bash -c "celery -A Intership_project beat -l info"
    env_file:
      - .env.prod
    volumes:
      - .:/Intership_project
    depends_on:
      - web
      - redis

  dashboard:
    build: .
    command: bash -c "celery -A Intership_project flower --port=5555"
    ports:
      - 5555:5555
    env_file:
      - .env.prod
    volumes:
      - .:/Intership_project
    depends_on:
      - web
      - redis
      - celery

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/Intership_project/static/
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: