# Generated by Django 4.0.3 on 2022-03-23 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('cash_balance', models.DecimalField(decimal_places=2, default=0, max_digits=25)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=128)),
                ('car_model', models.CharField(max_length=128)),
                ('engine_type', models.CharField(choices=[('g', 'Gas engine'), ('d', 'Diesel engine'), ('e', 'Electric engine')], default='g', max_length=20)),
                ('engine_power', models.IntegerField(blank=True, null=True)),
                ('transmission', models.CharField(choices=[('A', 'Automatic'), ('M', 'Manual')], default='M', max_length=64)),
                ('color', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Showroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('location', django_countries.fields.CountryField(max_length=2)),
                ('parameters_car', models.JSONField()),
                ('cash_balance', models.DecimalField(decimal_places=2, max_digits=25)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updates', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('year_foundation', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuppliersGarage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=25)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.car')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierSalesHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=25)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=25)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.suppliersgarage')),
                ('showroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.showroom')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='ShowroomsGarage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=25)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=25)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updates', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.suppliersgarage')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='ShowroomCustomerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=25)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=25)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.showroomsgarage')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.advuser')),
                ('showroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.showroom')),
            ],
        ),
    ]
